apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: hostname
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
        - name: hostname
          image: david8bullet/hostname:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: hostname-service
spec:
  type: LoadBalancer
  selector:
    app: hostname
  ports:
    - protocol: TCP
      port: 8091
      targetPort : 8090

